// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDW7RsXBO_MfO44PHFnqzYuIYOcNccNH8',
    appId: '1:894806698727:web:282165aff6310303cc1042',
    messagingSenderId: '894806698727',
    projectId: 'vian-5fc12',
    authDomain: 'vian-5fc12.firebaseapp.com',
    storageBucket: 'vian-5fc12.firebasestorage.app',
    measurementId: 'G-4FZKLF3CQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_YkzeKITyoU_5eZ8iIcm-afi8gormrxk',
    appId: '1:894806698727:android:3ec0dddcb31933c9cc1042',
    messagingSenderId: '894806698727',
    projectId: 'vian-5fc12',
    storageBucket: 'vian-5fc12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrlC7b_AlM3S5mvfN_VfXlzTt48_yyd3A',
    appId: '1:894806698727:ios:3c243d69d957b9a9cc1042',
    messagingSenderId: '894806698727',
    projectId: 'vian-5fc12',
    storageBucket: 'vian-5fc12.firebasestorage.app',
    iosBundleId: 'com.example.vianAdmin',
  );
}
